
[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[[override]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver"

[[constraint]]
  branch = "master"
  name = "github.com/kballard/go-shellquote"

[prune]
  go-tests = true
  unused-packages = true
